<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
          DB::table('settings')->insert([
            [
                'id'                  => 1,
                'code'                => 'STG_1',
                'settingName'         => 'Delivery Charges',
                'settingValue'        => '6',
                'type'                => 'amount',
                'isActive'            => 1,
                'isDelete'            => 0,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '49.36.42.50',
                'editID'              => 'USR_1',
                'editDate'            => '2025-09-08 03:38:36',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
            [
                'id'                  => 2,
                'code'                => 'STG_2',
                'settingName'         => 'Tax Percentage',
                'settingValue'        => '10',
                'type'                => 'percent',
                'isActive'            => 1,
                'isDelete'            => 0,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '49.36.42.50',
                'editID'              => 'USR_1',
                'editDate'            => '2025-09-08 03:38:05',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
            [
                'id'                  => 3,
                'code'                => 'STG_3',
                'settingName'         => 'Delivery Radius',
                'settingValue'        => '3',
                'type'                => 'numeric',
                'isActive'            => 0,
                'isDelete'            => 1,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '2607:fea8:d62:1f00:d1a5:5f52:2dd2:693',
                'editID'              => 'USR_1',
                'editDate'            => '2023-08-04 23:22:33',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
            [
                'id'                  => 4,
                'code'                => 'STG_4',
                'settingName'         => 'Convenience Charges (Stripe %)',
                'settingValue'        => '0',
                'type'                => 'percent',
                'isActive'            => 1,
                'isDelete'            => 0,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '2405:201:1002:4871:e841:3045:3ccc:fb6d',
                'editID'              => 'USR_1',
                'editDate'            => '2023-09-26 14:05:41',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
            [
                'id'                  => 5,
                'code'                => 'STG_5',
                'settingName'         => 'Non Regular Toppings ',
                'settingValue'        => 'Premium Toppings',
                'type'                => 'text',
                'isActive'            => 1,
                'isDelete'            => 0,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '49.36.42.50',
                'editID'              => 'USR_1',
                'editDate'            => '2025-08-31 21:22:25',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
            [
                'id'                  => 6,
                'code'                => 'STG_6',
                'settingName'         => 'Regular Toppings ',
                'settingValue'        => 'Regular Toppings',
                'type'                => 'text',
                'isActive'            => 1,
                'isDelete'            => 0,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '49.36.42.50',
                'editID'              => 'USR_1',
                'editDate'            => '2025-08-31 21:39:11',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
            [
                'id'                  => 7,
                'code'                => 'STG_7',
                'settingName'         => 'Non Regular Topping Count',
                'settingValue'        => '2',
                'type'                => 'numeric',
                'isActive'            => 1,
                'isDelete'            => 0,
                'addID'               => null,
                'addIP'               => null,
                'addDate'             => null,
                'editIP'              => '49.36.42.50',
                'editID'              => 'USR_1',
                'editDate'            => '2025-09-10 03:50:42',
                'deleteIP'            => null,
                'deleteID'            => null,
                'deleteDate'          => null,
                'isUpdateCompulsory'  => null,
            ],
        ]);
    }
}
